# Generated by Django 3.2.13 on 2022-06-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('key', models.CharField(choices=[('A', 'A'), ('A#/Bb', 'A#/Bb'), ('B', 'B'), ('C', 'C'), ('C#/Db', 'C#/Db'), ('D', 'D'), ('D#/Eb', 'D#/Eb'), ('E', 'E'), ('F', 'F'), ('F#/Gb', 'F#/Gb'), ('G', 'G'), ('G#/Ab', 'G#/Ab')], max_length=5)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
