# Generated by Django 3.2.13 on 2022-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
